# Generated by Django 4.2 on 2023-05-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='doginfo',
            name='price',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='address',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='breed',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='img',
            field=models.ImageField(default=False, upload_to='pictures'),
        ),
    ]
