# Generated by Django 4.2 on 2023-05-21 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_phoneno_doginfo_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doginfo',
            name='d',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
