# Generated by Django 4.2 on 2023-05-21 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doginfo_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doginfo',
            name='d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
