# Generated by Django 4.2 on 2023-05-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_doginfo_d"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doginfo",
            name="d",
        ),
    ]
